version: '3.8'

services:
  app:
    env_file: ".env"
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env 
      - ./static:/app/static
      - data:/app/data
      - data_backup:/app/backup
    container_name: "${APP_NAME}_app"
    networks:
      - app_network
    environment:
      - DB_HOST=db
      - DB_USER=go4lage
      - DB_PASSWORD=go4lage
      - DB_NAME=go4lage
    restart: unless-stopped

  db:
    env_file: ".env"
    image: postgres:13
    environment:
      POSTGRES_USER: go4lage
      POSTGRES_PASSWORD: go4lage
      POSTGRES_DB: go4lage
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: "${APP_NAME}_db"
    networks:
      - app_network
    healthcheck:
      test: pg_isready -U go4lage -d go4lage
      interval: 5s
      timeout: 5s
    restart: unless-stopped

volumes:
  postgres_data:
  data:
  data_backup:

networks:
  app_network:
    driver: bridge
